# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('n0', models.CharField(max_length=50, verbose_name='nome')),
                ('i0', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('n0', models.CharField(max_length=100, verbose_name='nome_grupo')),
                ('blocos', models.ManyToManyField(blank=True, related_name='_b1_blocos_+', to='e4.B1')),
            ],
        ),
        migrations.CreateModel(
            name='D1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('n0', models.CharField(max_length=50, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='F0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('un', models.CharField(choices=[('mm', 'mm'), ('px', 'px')], default='mm', max_length=2)),
                ('w', models.CharField(max_length=10, verbose_name='largura')),
                ('h', models.CharField(max_length=10, verbose_name='altura')),
            ],
        ),
        migrations.CreateModel(
            name='F1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('n0', models.CharField(max_length=100, verbose_name='titulo')),
                ('ano', models.CharField(max_length=4)),
                ('sinopse', models.TextField()),
                ('duracao', models.CharField(blank=True, max_length=10, null=True)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('formato', models.CharField(blank=True, max_length=20, null=True)),
                ('diretores', models.ManyToManyField(to='e4.D1')),
            ],
        ),
        migrations.CreateModel(
            name='I0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('n0', models.CharField(max_length=30, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='I3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('creditos', models.CharField(max_length=200)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.F1')),
            ],
        ),
        migrations.CreateModel(
            name='M4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n0', models.CharField(max_length=30, verbose_name='nome')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='obss')),
            ],
        ),
        migrations.CreateModel(
            name='P3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=10, verbose_name='quantidade')),
                ('verso', models.BooleanField(verbose_name='frenteverso')),
                ('papel', models.CharField(blank=True, max_length=30, null=True)),
                ('gramatura', models.CharField(blank=True, max_length=10, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='obss')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.F0')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.M4')),
            ],
            options={
                'ordering': ['material', 'formato'],
            },
        ),
        migrations.CreateModel(
            name='T0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('n0', models.CharField(max_length=30, verbose_name='nome')),
                ('txt', models.TextField(verbose_name='txts(info/linha)')),
            ],
        ),
        migrations.CreateModel(
            name='T3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('tt', models.CharField(max_length=30, verbose_name='nome')),
                ('cit', models.TextField(verbose_name='citacao(info/linha)')),
                ('txt', models.TextField(verbose_name='txt')),
                ('ref', models.TextField(verbose_name='referencia/linha')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.A1')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.F1')),
            ],
        ),
        migrations.AddField(
            model_name='m4',
            name='formatos',
            field=models.ManyToManyField(blank=True, through='e4.P3', to='e4.F0'),
        ),
        migrations.AddField(
            model_name='b1',
            name='imagens',
            field=models.ManyToManyField(blank=True, to='e4.I3'),
        ),
        migrations.AddField(
            model_name='b1',
            name='informacoes',
            field=models.ManyToManyField(blank=True, to='e4.T0'),
        ),
        migrations.AddField(
            model_name='b1',
            name='logos',
            field=models.ManyToManyField(blank=True, to='e4.I0'),
        ),
        migrations.AddField(
            model_name='b1',
            name='textos',
            field=models.ManyToManyField(blank=True, to='e4.T3'),
        ),
    ]
