# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='f1',
            name='dx',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='p3',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='a1',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='a1',
            name='i0',
            field=models.TextField(verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='b1',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='d1',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='f0',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='f1',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='i0',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='i3',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='m4',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='t0',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='t3',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
