# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0003_auto_20170620_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='f1',
            name='t0',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo_original'),
        ),
    ]
