# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0005_auto_20170620_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='i1',
            name='h',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='i1',
            name='w',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
