# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import e4.models


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0006_auto_20170620_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i1',
            name='h',
            field=models.CharField(default=' ', editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='i1',
            name='img',
            field=models.ImageField(blank=True, height_field='h', null=True, upload_to=e4.models.I1.def_caminho, width_field='w'),
        ),
        migrations.AlterField(
            model_name='i1',
            name='w',
            field=models.CharField(default=' ', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
