# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0007_auto_20170620_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m0',
            name='formatos',
        ),
        migrations.RemoveField(
            model_name='p0',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='p0',
            name='material',
        ),
        migrations.DeleteModel(
            name='M0',
        ),
        migrations.DeleteModel(
            name='P0',
        ),
    ]
