# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0008_auto_20170620_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='M0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now=True)),
                ('n0', models.CharField(max_length=30, verbose_name='nome')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='obss')),
            ],
        ),
        migrations.CreateModel(
            name='P0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now=True)),
                ('q', models.CharField(max_length=10, verbose_name='quantidade')),
                ('verso', models.BooleanField(verbose_name='frenteverso')),
                ('papel', models.CharField(blank=True, max_length=30, null=True)),
                ('gramatura', models.CharField(blank=True, max_length=10, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='obss')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.F0')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4.M0')),
            ],
            options={
                'ordering': ['material', 'formato'],
            },
        ),
        migrations.AddField(
            model_name='m0',
            name='formatos',
            field=models.ManyToManyField(blank=True, through='e4.P0', to='e4.F0'),
        ),
    ]
