# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e4', '0010_auto_20170621_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='m0',
            name='blocos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e4.B0'),
        ),
    ]
