# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0003_auto_20170520_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a',
            old_name='r3',
            new_name='rel',
        ),
        migrations.RenameField(
            model_name='b',
            old_name='r3',
            new_name='rel',
        ),
        migrations.RenameField(
            model_name='d',
            old_name='r3',
            new_name='rel',
        ),
        migrations.RenameField(
            model_name='l8p',
            old_name='r3',
            new_name='rel',
        ),
        migrations.RenameField(
            model_name='v4r',
            old_name='r3',
            new_name='rel',
        ),
    ]
