# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0006_auto_20170523_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='V4',
            new_name='T2',
        ),
        migrations.RenameField(
            model_name='f7',
            old_name='v4',
            new_name='t2',
        ),
    ]
