# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0011_auto_20170523_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f7',
            name='r1',
        ),
    ]
