# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0014_auto_20170524_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f7',
            name='r1',
            field=models.ManyToManyField(blank=True, related_name='_f7_r1_+', to='f7.F7'),
        ),
    ]
