# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0015_auto_20170524_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f7',
            options={'ordering': ['n3']},
        ),
    ]
