# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0016_auto_20170524_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f7',
            options={'ordering': ['?']},
        ),
        migrations.AddField(
            model_name='t2',
            name='r1',
            field=models.ManyToManyField(blank=True, related_name='_t2_r1_+', to='f7.T2'),
        ),
    ]
