# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0017_auto_20170526_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t2',
            name='r1',
            field=models.ManyToManyField(blank=True, to='f7.T2'),
        ),
    ]
