# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import f7.models


class Migration(migrations.Migration):

    dependencies = [
        ('f7', '0018_auto_20170527_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f7',
            old_name='n3',
            new_name='n0',
        ),
        migrations.RenameField(
            model_name='t2',
            old_name='n3',
            new_name='n0',
        ),
        migrations.AddField(
            model_name='f7',
            name='h',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='f7',
            name='img',
            field=models.ImageField(blank=True, height_field='h', null=True, upload_to=f7.models.F7.def_caminho, width_field='w'),
        ),
        migrations.AddField(
            model_name='f7',
            name='w',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='f7',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='t2',
            name='d0',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
