# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='M8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.IntegerField()),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m8.C0')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
