# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m8', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m8',
            name='cor',
        ),
        migrations.DeleteModel(
            name='C0',
        ),
        migrations.DeleteModel(
            name='M8',
        ),
    ]
