# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m8', '0005_auto_20170531_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c4',
            options={'ordering': ['?']},
        ),
        migrations.AlterModelOptions(
            name='e1',
            options={'ordering': ['?']},
        ),
    ]
