# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m8', '0007_auto_20170604_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c4',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='e1',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
