# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m8', '0008_auto_20170604_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m8',
            name='cor',
            field=models.ManyToManyField(blank=True, to='m8.C0'),
        ),
    ]
