# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m8', '0009_auto_20170604_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m8',
            name='familia',
        ),
        migrations.DeleteModel(
            name='F8',
        ),
    ]
