# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='I0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('pae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=50)),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('pae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tptp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='i0.TP')),
            ],
        ),
        migrations.AddField(
            model_name='i0',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i0.TP'),
        ),
    ]
