# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i0', '0002_auto_20170406_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tp',
            options={'ordering': ['id']},
        ),
    ]
