# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i0', '0005_auto_20170406_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i0',
            name='cn',
            field=models.SlugField(default='i0<built-in function id>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='txt',
            name='dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='txt',
            name='hr',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
