# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i0', '0006_auto_20170406_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i0',
            name='cn',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
