# Generated by Django 3.1 on 2020-08-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i0', '0007_auto_20170406_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i0',
            name='tp',
            field=models.ForeignKey(limit_choices_to={'tptp__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='i0.tp'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='tptp',
            field=models.ForeignKey(blank=True, limit_choices_to={'tptp__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='i0.tp'),
        ),
        migrations.AlterField(
            model_name='txt',
            name='i0',
            field=models.OneToOneField(limit_choices_to={'tp_id': 2}, on_delete=django.db.models.deletion.CASCADE, to='i0.i0'),
        ),
        migrations.AlterField(
            model_name='txt',
            name='tp',
            field=models.ForeignKey(limit_choices_to={'tptp_id': 2}, on_delete=django.db.models.deletion.CASCADE, to='i0.tp'),
        ),
    ]
